---@class slotid
---@field public Unknown integer
---@field public Q integer
---@field public W integer
---@field public E integer
---@field public R integer
---@field public Summoner1 integer
---@field public Summoner2 integer
---@field public Item1 integer
---@field public Item2 integer
---@field public Item3 integer
---@field public Item4 integer
---@field public Item5 integer
---@field public Item6 integer
---@field public Item_Trinket integer
---@field public Recall integer
---@field public SpecialAttack integer
---@field public SpecialSpell1 integer
---@field public Auto1 integer
---@field public Auto2 integer
---@field public Auto3 integer

---@type slotid
_G.slotid = { }