---@class spelldata
---@field public spell_name string
---@field public hash number
---@field public mSpellTags string[]
---@field public mDataValues_BaseDamage number[]
---@field public cooldownTime number[]
---@field public delayCastOffsetPercent number
---@field public delayTotalTimePercent number
---@field public mTurnSpeedScalar number
---@field public castRange number[]
---@field public castRangeDisplayOverride number[]
---@field public castRadius number[]
---@field public castConeDistance number
---@field public mMissileSpec_mMissileWidth number
---@field public castType integer
---@field public castFrame number
---@field public missileSpeed number
---@field public mLineWidth number
